In [1]:
import numpy as np

In [4]:
n = np.array([])
n

array([], dtype=float64)

In [5]:
print(n)

[]


In [6]:
# attributes

In [7]:
n.shape

(0,)

In [8]:
n.dtype

dtype('float64')

In [9]:
n.size

0

In [10]:
len(n)

0

In [11]:
a = np.array([4,5,6,7,89])
a

array([ 4,  5,  6,  7, 89])

In [12]:
a.shape

(5,)

In [13]:
b = np.array([[3,4,5],[6,33,88]])
b

array([[ 3,  4,  5],
       [ 6, 33, 88]])

In [14]:
b.shape

(2, 3)

In [15]:
c = np.array([[4,5,8],[13,19,11],[6,7,1],[3,6,20]])
c

array([[ 4,  5,  8],
       [13, 19, 11],
       [ 6,  7,  1],
       [ 3,  6, 20]])

In [16]:
c.shape

(4, 3)

In [18]:
d = np.array([[[8,81],[7,71],[6,61]],[[9,91],[4,41],[18,181]]])
d

array([[[  8,  81],
        [  7,  71],
        [  6,  61]],

       [[  9,  91],
        [  4,  41],
        [ 18, 181]]])

In [19]:
d.shape

(2, 3, 2)

### Accessing the Elements

In [20]:
c[0][1]

5

In [21]:
c[0][1:]

array([5, 8])

In [23]:
c[1:][1]

array([6, 7, 1])

In [24]:
c[1:,1]

array([19,  7,  6])

In [25]:
c[1,:]

array([13, 19, 11])

In [27]:
d[:,2,:]

array([[  6,  61],
       [ 18, 181]])

In [28]:
d[1,1,:]

array([ 4, 41])

In [29]:
d[:,:2,0]

array([[8, 7],
       [9, 4]])

#### Modifying Values

In [30]:
a

array([ 4,  5,  6,  7, 89])

In [31]:
a[0] = 40

In [32]:
a

array([40,  5,  6,  7, 89])

#### More Array Creation Functions

In [34]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [37]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [39]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(1,100,5) # we define gap 5

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [41]:
np.linspace(1,100,20) # we define count of values 20

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.random.rand(3,4) # values are between 0.0 to 1.0

array([[0.73638686, 0.46915309, 0.62417173, 0.29861158],
       [0.75041831, 0.50898879, 0.11186721, 0.33040768],
       [0.50236098, 0.03157567, 0.80812298, 0.59510392]])

In [52]:
np.random.rand(3,4)*20

array([[ 6.26613011, 12.42087456, 19.66877465,  3.05544552],
       [ 8.80169199,  3.73068743,  0.87487462,  9.97446848],
       [ 9.47359615,  3.89096033,  1.88713276,  5.43277525]])

In [53]:
np.random.randint(1,100) # ranging between 1 to 100

40

In [55]:
np.random.randint(1,100,4) # ranging between 1 to 100, and total 4 values

array([22, 12,  3, 94])

In [56]:
np.random.randint(1,100,(4,7)) # ranging between 1 to 100, and total 4x7 matrix

array([[21, 41, 54, 95,  2,  5, 30],
       [ 7, 81, 62, 27, 47,  4, 92],
       [12, 66, 85, 12, 27, 82, 75],
       [80, 74, 57, 77, 66, 82, 24]])

In [57]:
np.random.randn(5)

array([ 1.57406506,  0.05616548, -0.8727348 ,  0.68325614,  0.00574858])

In [43]:
import random

In [50]:
random.randint(1,6)

5

#### Operations on Arrays

In [60]:
k = np.linspace(1,100,20)
k

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [61]:
k.shape

(20,)

In [62]:
k1 = k.reshape(4,5)
k1

array([[  1.        ,   6.21052632,  11.42105263,  16.63157895,
         21.84210526],
       [ 27.05263158,  32.26315789,  37.47368421,  42.68421053,
         47.89473684],
       [ 53.10526316,  58.31578947,  63.52631579,  68.73684211,
         73.94736842],
       [ 79.15789474,  84.36842105,  89.57894737,  94.78947368,
        100.        ]])

In [63]:
k1.shape

(4, 5)

In [67]:
np.vsplit(k1,2)

[array([[ 1.        ,  6.21052632, 11.42105263, 16.63157895, 21.84210526],
        [27.05263158, 32.26315789, 37.47368421, 42.68421053, 47.89473684]]),
 array([[ 53.10526316,  58.31578947,  63.52631579,  68.73684211,
          73.94736842],
        [ 79.15789474,  84.36842105,  89.57894737,  94.78947368,
         100.        ]])]

In [68]:
k1*3

array([[  3.        ,  18.63157895,  34.26315789,  49.89473684,
         65.52631579],
       [ 81.15789474,  96.78947368, 112.42105263, 128.05263158,
        143.68421053],
       [159.31578947, 174.94736842, 190.57894737, 206.21052632,
        221.84210526],
       [237.47368421, 253.10526316, 268.73684211, 284.36842105,
        300.        ]])

#### Statstical Functions

In [70]:
k1

array([[  1.        ,   6.21052632,  11.42105263,  16.63157895,
         21.84210526],
       [ 27.05263158,  32.26315789,  37.47368421,  42.68421053,
         47.89473684],
       [ 53.10526316,  58.31578947,  63.52631579,  68.73684211,
         73.94736842],
       [ 79.15789474,  84.36842105,  89.57894737,  94.78947368,
        100.        ]])

In [73]:
c

array([[ 4,  5,  8],
       [13, 19, 11],
       [ 6,  7,  1],
       [ 3,  6, 20]])

In [74]:
c.sum()

103

In [75]:
c.sum(axis=1)

array([17, 43, 14, 29])

In [76]:
c.sum(axis=0)

array([26, 37, 40])

In [78]:
c.min(axis=0)

array([3, 5, 1])

In [79]:
c.max()

20

In [80]:
c.std()

5.794513688730824

In [81]:
c.std(axis=1)

array([1.69967317, 3.39934634, 2.62466929, 7.40870359])

#### File Handling

In [82]:
c

array([[ 4,  5,  8],
       [13, 19, 11],
       [ 6,  7,  1],
       [ 3,  6, 20]])

In [83]:
np.save('myarray',c)

In [84]:
# Loading the file
myobj = np.load('myarray.npy')


In [85]:
myobj

array([[ 4,  5,  8],
       [13, 19, 11],
       [ 6,  7,  1],
       [ 3,  6, 20]])

In [97]:
np.savetxt(fname='myfile.csv',X=c,delimiter=',',header='a,b,c',fmt='%d')

In [98]:
t = np.loadtxt('myfile.csv',delimiter=',',dtype=int)

In [99]:
t

array([[ 4,  5,  8],
       [13, 19, 11],
       [ 6,  7,  1],
       [ 3,  6, 20]])